# Generated by Django 2.2.1 on 2019-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoRsp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.TextField()),
                ('seaLevel', models.TextField()),
                ('time', models.TextField()),
                ('date', models.TextField()),
                ('serialTag', models.TextField()),
                ('position', models.TextField()),
            ],
        ),
    ]
